### ISSUE TITLE
PEM/OpenSSL error

### ISSUE THREAD

**Issue by LeVadim** [PayU/apple-pay#2]
Hello!

Would you be able to advise me on this error?

 CN = Apple Application Integration CA - G3, OU = Apple Certification Authority, O = Apple Inc., C = US *** error 20 at 1 depth lookup:unable to get loca
l issuer certificate"
    #code: 0
    #file: "./vendor/payu/apple-pay/src/ApplePay/Decoding/OpenSSL/OpenSslService.php"
    #line: 29
    trace: {

Thank you!!!

**Comment by trydocatch** [comment]
Hi,

Probably one of the certificates used as argument is not what is expected.
You could refer to the test OpenSslServiceTest::testValidateCertificateChainSuccess and check what is different in your implementation.
