### ISSUE TITLE
Questions about the example

### ISSUE THREAD

**Issue by Hywan** [PayU/apple-pay#3]
Hello :-),

In your example, there is a `$privateKey` variable:

https://github.com/PayU/apple-pay/blob/a7982095aabf97f4d74bb2b2fb5f1830ab3d00f5/examples/decode_token.php#L10-L11

The comment says it is the private key used to create the CSR. I don't get it. When creating the payment processing certificate, a `.certSigningRequest` file is generated and given to Apple, which, in turn, gives us a `.cert` file (https://help.apple.com/developer-account/#/devb2e62b839?sub=devf31990e3f). What information do we need to extract from what?

Thanks for your help!

**Comment by trydocatch** [comment]
Hi,

If you go to "iOS Merchant ID Settings" page (https://developer.apple.com/account/ios/identifier/merchant/) in your Apple Developer Account and try to create a new "Apple Pay Payment Processing Certificate", you'll see that you'll have to provide a CSR that can be obtained in two ways:
 - Obtain a CSR file from your Payment Provider (Contact your payment provider to obtain a properly formatted CSR for you to upload and create your certificate.)
 - Create a CSR file. (Optional) (To create a CSR file without a payment provider, follow the instructions below to create one using Keychain Access. In the Applications folder on your Mac, open the Utilities folder and launch Keychain Access)
 
If you go the first way, you'll have to generate a private key before generating the CSR. That is the key that is being used in the example.
If you go the second way, which is specific to MacOs, I can't tell you where the private key is, but it probably can be extracted somehow.

Best regards,
Daniel

**Comment by webdesign7** [comment]
@trydocatch  can you please elaborate .. how can we get that key ? if we're using option1

**Comment by trydocatch** [comment]
@webdesign7 Option 2 is something specific to MacOs and I'm not able to help with that information

**Comment by rmbaumer** [comment]
@webdesign7 did you ever figure out which key and which format to use?
